### ISSUE TITLE
Comments 1-6

### ISSUE THREAD

**Issue by phyro** [postrv/ProjectEuler#1]
Good job!

Now try doing this:

problem 2: write fibonacci using recursion. Think about why it's slow and how to make it fast while keeping recursion
problem 4: you can have a single return for https://github.com/postrv/ProjectEuler/blob/master/Euler4.py#L12 Also try using `for` loops instead of `while` in this case
problem 6: make it a oneliner. There are likely also different ways to compute this if you visualize it (I've not tried it so I'm not 100% sure)

**Comment by postrv** [comment]
Done all the required changes 👍
